// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Explains the use of dental tools.
 *
 * - dentalToolExplanation - A function that explains the usage of dental tools.
 * - DentalToolExplanationInput - The input type for the dentalToolExplanation function.
 * - DentalToolExplanationOutput - The return type for the dentalToolExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DentalToolExplanationInputSchema = z.object({
  toolName: z.string().describe('The name of the dental tool to explain.'),
  patientQuestion: z.string().describe('The patient\'s question about the tool.'),
});
export type DentalToolExplanationInput = z.infer<typeof DentalToolExplanationInputSchema>;

const DentalToolExplanationOutputSchema = z.object({
  explanation: z.string().describe('A clear and concise explanation of the dental tool and its benefits.'),
});
export type DentalToolExplanationOutput = z.infer<typeof DentalToolExplanationOutputSchema>;

export async function dentalToolExplanation(input: DentalToolExplanationInput): Promise<DentalToolExplanationOutput> {
  return dentalToolExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dentalToolExplanationPrompt',
  input: {schema: DentalToolExplanationInputSchema},
  output: {schema: DentalToolExplanationOutputSchema},
  prompt: `You are a helpful dental assistant explaining dental tools to patients.\n\nPatient Question: {{{patientQuestion}}}\nTool Name: {{{toolName}}}\n\nExplain the function and benefits of the tool in a way that is easy for patients to understand.`,
});

const dentalToolExplanationFlow = ai.defineFlow(
  {
    name: 'dentalToolExplanationFlow',
    inputSchema: DentalToolExplanationInputSchema,
    outputSchema: DentalToolExplanationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
